"""initial_schema

Revision ID: 7688e2cafe6b
Revises: a5587aaded64
Create Date: 2026-05-05 00:32:21.258136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7688e2cafe6b'
down_revision: Union[str, Sequence[str], None] = 'a5587aaded64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
