"""initial_schema

Revision ID: a5587aaded64
Revises:
Create Date: 2026-05-04 23:49:25.884789

Enum labels use Python enum *values* (e.g. active, received) to match SQLAlchemy persistence.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a5587aaded64"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("full_name", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "inactive",
                "suspended",
                name="user_status",
            ),
            nullable=False,
        ),
        sa.Column("department_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.Integer(), nullable=True),
        sa.Column("detail_json", sa.Text(), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_actor_user_id"), "audit_logs", ["actor_user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_resource_id"), "audit_logs", ["resource_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"), "audit_logs", ["resource_type"], unique=False
    )
    op.create_table(
        "letters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("serial_no", sa.String(length=30), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("received_from", sa.String(length=255), nullable=False),
        sa.Column("pdf_path", sa.String(length=500), nullable=False),
        sa.Column(
            "priority",
            sa.Enum(
                "low",
                "normal",
                "high",
                "urgent",
                name="letter_priority",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "received",
                "under_review",
                "returned_for_correction",
                "rejected",
                "processed",
                "closed",
                name="letter_status",
            ),
            nullable=False,
        ),
        sa.Column("department_id", sa.Integer(), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["closed_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_letters_id"), "letters", ["id"], unique=False)
    op.create_index(op.f("ix_letters_serial_no"), "letters", ["serial_no"], unique=True)
    op.create_table(
        "login_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email_attempted", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("failure_reason", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_login_logs_created_at"), "login_logs", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_login_logs_email_attempted"),
        "login_logs",
        ["email_attempted"],
        unique=False,
    )
    op.create_index(op.f("ix_login_logs_id"), "login_logs", ["id"], unique=False)
    op.create_index(op.f("ix_login_logs_success"), "login_logs", ["success"], unique=False)
    op.create_index(op.f("ix_login_logs_user_id"), "login_logs", ["user_id"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "letter_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("letter_id", sa.Integer(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "approve",
                "reject",
                "return_for_correction",
                "route",
                "assign_consultant",
                "reassign_consultant",
                "consultant_status_update",
                "resolution_note",
                "solution_file_upload",
                "transfer_assignment",
                "review_solution",
                "final_comment",
                "close_issue",
                name="letter_action_type",
            ),
            nullable=False,
        ),
        sa.Column("comment", sa.String(length=2000), nullable=False),
        sa.Column("acted_by", sa.Integer(), nullable=False),
        sa.Column("from_department_id", sa.Integer(), nullable=True),
        sa.Column("to_department_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["acted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["from_department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["letters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_department_id"],
            ["departments.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_letter_actions_id"), "letter_actions", ["id"], unique=False)
    op.create_table(
        "letter_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("letter_id", sa.Integer(), nullable=False),
        sa.Column("consultant_id", sa.Integer(), nullable=False),
        sa.Column("assigned_by", sa.Integer(), nullable=False),
        sa.Column("deadline_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "work_status",
            sa.Enum(
                "assigned",
                "in_progress",
                "resolved",
                "transferred",
                name="assignment_work_status",
            ),
            nullable=False,
        ),
        sa.Column("resolution_note", sa.String(length=2000), nullable=True),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["consultant_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["letters.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_letter_assignments_id"), "letter_assignments", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_letter_assignments_letter_id"),
        "letter_assignments",
        ["letter_id"],
        unique=False,
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("letter_id", sa.Integer(), nullable=True),
        sa.Column("link_path", sa.String(length=512), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["letter_id"],
            ["letters.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notifications_created_at"), "notifications", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_notifications_id"), "notifications", ["id"], unique=False)
    op.create_index(
        op.f("ix_notifications_letter_id"), "notifications", ["letter_id"], unique=False
    )
    op.create_index(
        op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False
    )
    op.create_table(
        "assignment_solution_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["letter_assignments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assignment_solution_files_assignment_id"),
        "assignment_solution_files",
        ["assignment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_assignment_solution_files_id"),
        "assignment_solution_files",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_assignment_solution_files_id"), table_name="assignment_solution_files"
    )
    op.drop_index(
        op.f("ix_assignment_solution_files_assignment_id"),
        table_name="assignment_solution_files",
    )
    op.drop_table("assignment_solution_files")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_letter_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_created_at"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_letter_assignments_letter_id"), table_name="letter_assignments")
    op.drop_index(op.f("ix_letter_assignments_id"), table_name="letter_assignments")
    op.drop_table("letter_assignments")
    op.drop_index(op.f("ix_letter_actions_id"), table_name="letter_actions")
    op.drop_table("letter_actions")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_login_logs_user_id"), table_name="login_logs")
    op.drop_index(op.f("ix_login_logs_success"), table_name="login_logs")
    op.drop_index(op.f("ix_login_logs_id"), table_name="login_logs")
    op.drop_index(op.f("ix_login_logs_email_attempted"), table_name="login_logs")
    op.drop_index(op.f("ix_login_logs_created_at"), table_name="login_logs")
    op.drop_table("login_logs")
    op.drop_index(op.f("ix_letters_serial_no"), table_name="letters")
    op.drop_index(op.f("ix_letters_id"), table_name="letters")
    op.drop_table("letters")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_user_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")

    op.execute("DROP TYPE IF EXISTS assignment_work_status")
    op.execute("DROP TYPE IF EXISTS letter_action_type")
    op.execute("DROP TYPE IF EXISTS letter_status")
    op.execute("DROP TYPE IF EXISTS letter_priority")
    op.execute("DROP TYPE IF EXISTS user_status")
    # ### end Alembic commands ###
