"""optimize_list_api_indexes

Revision ID: e3dacdb0f699
Revises: 7688e2cafe6b
Create Date: 2026-05-05 01:05:55.315969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3dacdb0f699'
down_revision: Union[str, Sequence[str], None] = '7688e2cafe6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_assignment_solution_files_uploaded_by'), 'assignment_solution_files', ['uploaded_by'], unique=False)
    op.create_index(op.f('ix_letter_actions_acted_by'), 'letter_actions', ['acted_by'], unique=False)
    op.create_index(op.f('ix_letter_actions_action'), 'letter_actions', ['action'], unique=False)
    op.create_index(op.f('ix_letter_actions_created_at'), 'letter_actions', ['created_at'], unique=False)
    op.create_index(op.f('ix_letter_actions_letter_id'), 'letter_actions', ['letter_id'], unique=False)
    op.create_index(op.f('ix_letter_assignments_assigned_by'), 'letter_assignments', ['assigned_by'], unique=False)
    op.create_index(op.f('ix_letter_assignments_consultant_id'), 'letter_assignments', ['consultant_id'], unique=False)
    op.create_index(op.f('ix_letter_assignments_deadline_at'), 'letter_assignments', ['deadline_at'], unique=False)
    op.create_index(op.f('ix_letter_assignments_is_active'), 'letter_assignments', ['is_active'], unique=False)
    op.create_index(op.f('ix_letter_assignments_work_status'), 'letter_assignments', ['work_status'], unique=False)
    op.create_index(op.f('ix_letters_created_at'), 'letters', ['created_at'], unique=False)
    op.create_index(op.f('ix_letters_created_by'), 'letters', ['created_by'], unique=False)
    op.create_index(op.f('ix_letters_department_id'), 'letters', ['department_id'], unique=False)
    op.create_index(op.f('ix_letters_status'), 'letters', ['status'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_letters_status'), table_name='letters')
    op.drop_index(op.f('ix_letters_department_id'), table_name='letters')
    op.drop_index(op.f('ix_letters_created_by'), table_name='letters')
    op.drop_index(op.f('ix_letters_created_at'), table_name='letters')
    op.drop_index(op.f('ix_letter_assignments_work_status'), table_name='letter_assignments')
    op.drop_index(op.f('ix_letter_assignments_is_active'), table_name='letter_assignments')
    op.drop_index(op.f('ix_letter_assignments_deadline_at'), table_name='letter_assignments')
    op.drop_index(op.f('ix_letter_assignments_consultant_id'), table_name='letter_assignments')
    op.drop_index(op.f('ix_letter_assignments_assigned_by'), table_name='letter_assignments')
    op.drop_index(op.f('ix_letter_actions_letter_id'), table_name='letter_actions')
    op.drop_index(op.f('ix_letter_actions_created_at'), table_name='letter_actions')
    op.drop_index(op.f('ix_letter_actions_action'), table_name='letter_actions')
    op.drop_index(op.f('ix_letter_actions_acted_by'), table_name='letter_actions')
    op.drop_index(op.f('ix_assignment_solution_files_uploaded_by'), table_name='assignment_solution_files')
    # ### end Alembic commands ###
